# Runs conda-lock against environment.yml for reproducible environments
# Runs on any opened PR
name: conda-lock-test

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  condalock:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install conda-lock
        run: |
          python -m pip install conda-lock
      - name: Update lockfiles
        run: |
          pushd environments/conda-forge-build
          ../../scripts/update_locks.sh
